name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@b4ffde65f69735febad8c6182f91ea7f1d183b7b

      - uses: pnpm/action-setup@fe02b3b
        with:
          version: 10.33.0

      - uses: actions/setup-node@1a4442caab129478691015c6976ebb13592f26cc
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
